# Generated by Django 3.2.8 on 2021-11-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=254)),
                ('blog_date', models.DateTimeField(auto_now=True)),
                ('blog_description', models.TextField(default='', null=True)),
                ('blog_verdict', models.CharField(default='', max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
