# Generated by Django 3.2.8 on 2021-11-28 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_sizes'),
        ('profiles', '0001_initial'),
        ('reviews', '0002_auto_20211126_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreview',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='userreview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='review_rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile'),
        ),
    ]
